### ISSUE TITLE
Defining the location source

### ISSUE THREAD

**Issue by Desertsnowman** [FacetWP/facetwp-map#1]
@mgibbs189 - I'm not sure how to handle the location source field. I simply put a text field in the settings page for the slug of the field and used "location" as the default. 
It's currently required to be the `lat, lng` format as used in the proximity facet type.

Also thought of adding a `field="slug"` shortcode attribute to override setting.

thoughts?

**Comment by mgibbs189** [comment]
We might need a "Location source" dropdown, so the users can choose between 1 or 2 custom fields.

If 1 custom field, then we'll assume it's a comma-separated string. Do minimal processing, like stripping out anything that's not 0-9, "-", "," or ".".

If 2 custom fields, then provide 2 input boxes to let users choose the latitude and longitude fields.

**Comment by Desertsnowman** [comment]
@mgibbs189 - ye that is a good option.
I'll look at adding that.

**Comment by Desertsnowman** [comment]
@mgibbs189 - perhaps have an option for ordering in comma separated. My first test was in `lat,lng` and hat to manually alter it to be `lng,lat`
