### ISSUE TITLE
Update to MarkerClusterer 1.0.1

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#10]
From ticket #5030:

There is a bug with markercluster v1.0 which is explained here: https://github.com/googlemaps/js-marker-clusterer/issues/86 

Basically if you have 2 items on the same space, the cluster disappears when you click it. 

It has been updated the version 1.0.1 which is here: https://github.com/googlemaps/v3-utility-library/blob/master/markerclusterer/src/markerclusterer.js

**Comment by mgibbs189** [comment]
Fixed in c4f539c

**Comment by Desertsnowman** [comment]
Sweet! Thanks.
