### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#12]
**Planning phase, no development yet**

We'll need to add a hook to let users control the marker icon(s).

Users should be able to change the default marker, as well as create their own custom marker logic (e.g. markers for specific post types, or specific categories, etc).

At this point, I don't think there needs to be a UI for it... the hook just needs to be pretty flexible to support the above scenarios.

**Comment by Desertsnowman** [comment]
@mgibbs189 it's already there as `facetwp_map_marker_args` can see it on https://github.com/FacetWP/facetwp-map/blob/master/classes/fwp_map.php#L285

**Comment by mgibbs189** [comment]
@Desertsnowman can you put together an example (gist) of how to change the marker icon using the aforementioned hook?

**Comment by Desertsnowman** [comment]
@mgibbs189 absolutely. I'll set one up for you tomorrow morning.

**Comment by Desertsnowman** [comment]
@mgibbs189 example - 
```php
add_filter( 'facetwp_map_marker_args', function ( $args ) {
	$args['icon'] = 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png';
	return $args;
} );
```

**Comment by Desertsnowman** [comment]
Example setting the icon based on the `$args['title']`
![markers](https://cloud.githubusercontent.com/assets/307466/21741211/b4e7d102-d4d7-11e6-89a1-4e4d91e51421.png)

**Comment by adammontague** [comment]
Could this be used with Advanced Custom Field checkbox values somehow?

**Comment by Desertsnowman** [comment]
Can you elaborate a little?

**Comment by adammontague** [comment]
Sure, so for example an Advanced Custom Fields checkbox field with options such like; Hotel, B&B, Caravan Park.

The map markers would then show an appropriate icon based on that selection.

**Comment by Desertsnowman** [comment]
oh, sure. in the `$args` of the filter there's a `$args['id']`. You would simply do a `get_field( $args['id'], 'the_field_slug')` ( or what ever ACF uses ) then change the icon depending on the value.

**Comment by adammontague** [comment]
I'd really appreciate an example code snippet if you wouldn't mind?

**Comment by Corporatic** [comment]
Hi @Desertsnowman,

Thanks for your help. I need a bit more from you, please.

I´m showing 2 post types in my map (posts and mycpt) and I want to show a different icon for each one of them. Could you give me a code for that?

Thanks a million

Regards

**Comment by HerAryan** [comment]
Hi, can you tell me how to add argument for custom post type taxonomy?
To elaborate:
I'm using filter that your have provided, and I want to use different marker icon by referring to main post tag of that post.
Best regards
