### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#14]
Warning: Illegal string offset 'single' in /www/wp-content/plugins/facetwp-map/classes/fwp_map.php on line 197

**Comment by Desertsnowman** [comment]
This is really odd. do you have any context to the error? Did you find it or did a user?

**Comment by raphaelkross** [comment]
@Desertsnowman It was reported by a customer - ticket 5211

**Comment by Desertsnowman** [comment]
Thanks, taking a look

**Comment by Desertsnowman** [comment]
I can't replicate this. Can anyone else?

**Comment by mgibbs189** [comment]
@Desertsnowman try a clean install (removing all settings), and enabling `WP_DEBUG`

**Comment by Desertsnowman** [comment]
I'm sure I did... hmmm

**Comment by Desertsnowman** [comment]
DOH! lol - would help if I use the right DB
