### ISSUE TITLE
Markers grouping even when disabled

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#15]
Ticket #5269

v1.0.3 - Even when the `Group Markers` toggle is off, the map still groups results. Also, when Group is enabled, on the next admin reload, the setting apparently returns to off...

**Comment by ckgg** [comment]
This problem must be conditional because I have Group Markers off in v1.0.3 and it works correctly.

**Comment by mgibbs189** [comment]
Closing, unable to duplicate.
