### ISSUE TITLE
Non-geocoded posts still appear in the map

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#18]
Since they don't have coordinates, they default to (0,0)... just West of Nigeria 😨 

We should prevent non-geocoded (or improperly geocoded) items from appearing at all.

Ref: Help Scout #5408

**Comment by Desertsnowman** [comment]
@mgibbs189 will need to make a disclaimer stating that if your just West of Nigeria, you can't use this addon.

**Comment by mgibbs189** [comment]
@Desertsnowman LOL

**Comment by mgibbs189** [comment]
@Desertsnowman apparently this issue is still happening on 1.0.4: http://208.113.164.207/cerca/

The user has 2 separate fields (1 for latitude, 1 for longitude).

**Comment by Desertsnowman** [comment]
thanks, checking it now.

**Comment by Desertsnowman** [comment]
@mgibbs189 - no idea whats when on here - but for some reason things went all neutral zone and undid the fix.
https://github.com/FacetWP/facetwp-map/commit/ea1ff16c04adc9d1017c3f3d7e96d9cd526884b1#diff-12680e091f65b08fc0cd37a442f72faf
