### ISSUE TITLE
Decouple max manual zoom from max auto zoom

### ISSUE THREAD

**Issue by ckgg** [FacetWP/facetwp-map#19]
The new Max Zoom setting controls two things: 1) the auto zoom used
while filtering, and 2) the maximum level the user can reach when
manually zooming the map.

It would be really nice if these were decoupled. This would allow, for example, the user
to be able to manually zoom as much as they like (i.e., 20), but the map
to auto zoom less (say, 14 or 15).

**Comment by mgibbs189** [comment]
@Desertsnowman is this possible using any of the existing hooks?

**Comment by Desertsnowman** [comment]
@mgibbs189 - I tried to get this while making it. unfortunately it's not possible ( or at least I'm not sure)
I'll take another look what I can find.
