### ISSUE TITLE
infobox content

### ISSUE THREAD

**Issue by Desertsnowman** [FacetWP/facetwp-map#2]
For the popup infobox, I'm currently using the `post_title` and the `post_excerpt`
Do you think this is suffecient as the default or should I add a little more like including `featured_image`?

I have added a filter `facetwp_map_infobox_content` to allow you to add your own content.
Which I think is a good option for customizing it.

**Comment by mgibbs189** [comment]
(via #4):  We could add a textarea box (in admin) to let users add custom code:

```php
<div class="mytitle"><?php the_title(); ?></div>
```

And perhaps make it filterable:

```php
$html = apply_filters( 'facetwp_map_marker_html', $html, $post_id );
```
