### ISSUE TITLE
FEATURE REQUEST: Custom Map Pin

### ISSUE THREAD

**Issue by noahkuhn** [FacetWP/facetwp-map#21]
I would love to have the option to upload a custom map pin instead of defaulting to the generic Google one. I may have a crack at adding it, but I'm sure you'd be significantly faster than I. Thanks!

**Comment by ckgg** [comment]
The filter described here worked for me, for this purpose:
https://github.com/FacetWP/facetwp-map/issues/12#issuecomment-271075498
:)

**Comment by noahkuhn** [comment]
Totally missed that. Thanks...
