### ISSUE TITLE
Default location for a map with zero locations?

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#22]
@Desertsnowman what do you think we should do for a map that has no active locations? Should we add an option for a "default" fallback location?

**Comment by Desertsnowman** [comment]
@mgibbs189 - we could do a map center.

**Comment by mgratch** [comment]
I was starting to implement this yesterday when I was having trouble deciding if it should be a blank map centered on the default location or a different pint on the default location.

Thoughts?  I am leaning towards a blank map.

**Comment by mgibbs189** [comment]
@mgratch agreed, it should just be a blank map centered on the default location.

**Comment by mgratch** [comment]
see #24
