### ISSUE TITLE
Notice error with MailPoet

### ISSUE THREAD

**Issue by sebastienserre** [FacetWP/facetwp-map#28]
Hello
Got error: `Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/facetwp-map/classes/facetwp_map/ui/page.php on line 90 ` when trying to add image in a newsletter with MailPoet 2.7.8
![capture_016](https://cloud.githubusercontent.com/assets/3902621/23943978/84722940-0971-11e7-8949-2256e0ebfc83.jpg)

Got mail exchange with David Cramer from your support

**Comment by mgibbs189** [comment]
Thanks @sebastienserre
