### ISSUE TITLE
Enhancement: Add class to list item when corresponding pin is clicked

### ISSUE THREAD

**Issue by philipb2** [FacetWP/facetwp-map#29]
I have a suggesting or feature request. Add a css class to the list items when clicking the pin on the map. Similar to this example here:
https://cardinalwp.com

When clicking the pin then “list-focus” class is added. I am not asking for scroll effect etc but it would be nice to highlight the item when the pin is clicked. Scroll to etc would be nice of course.

**Comment by mgibbs189** [comment]
Hey @philipb2 thanks for the suggestion. I'm not sure this can be universally "built-in", especially since the template will vary greatly from site to site.

TBH this might be better as a tutorial or something (showing how to set up the template, and describing the custom code needed)...

**Comment by philipb2** [comment]
Yes you are right. Since the list-items (loop) are set up different every time by the user its quite difficult to have it working out of the box.

I have seen this "feature" on several maps (which is more or less all custom built) and I think it would be a nice feature to have so if you could, when you have time, write a tutorial then I would really love it.

**Comment by ckgg** [comment]
Nice suggestion, @philipb2.  +1 for tutorial.  :)

**Comment by mgibbs189** [comment]
Off the top of my head, it's definitely possible and would require 3 steps:

1. Add a post ID attribute to each map marker, e.g.

```html
<div class="marker-item" data-pid="123">Marker content</div>
```

2. Adding a similar attribute to each result item, e.g.

```html
<div class="result-item" data-pid="123">The result content</div>
```

3. Add a javascript click handler. When a marker is clicked, look up the marker content's `data-pid`, then add a CSS class to a result item with the same attribute, e.g.

```js
// Pseudo-code
$(document).on('click', '.marker', function() {
  var pid = $(this).find('.marker-item').attr('data-pid');
  $('.result-item').removeClass('highlighted'); // unselect results
  $('.result-item[data-pid=' + pid + ']').addClass('highlighted'); // select item
});
```

**Comment by philipb2** [comment]
For one reason or another I can't get this to work though I do appreciate the steps above. I will keep an eye out for a tutorial if you one day will have time to show the template etc.

**Comment by vencreative** [comment]
This would be a great function if anyone knows how to do.
