### ISSUE TITLE
Using addresses instead og lat, long? 

### ISSUE THREAD

**Issue by 1KDevelopment** [FacetWP/facetwp-map#30]
Hi there, 

this is not so much an issue but more of a question: 

is it possible to use addresses instead of lag, long coordinates? Perhaps to convert is before being used by the map. 

Am asking as I have a shit load of addresses stored on posts and it would be a pain to have to convert these manually and add yet another field to them :-/ 

Thanks a lot in advance :-)

**Comment by mgibbs189** [comment]
Unfortunately not, the calculations require lat/longs, and converting all those addresses to coordinates on-the-fly would be incredibly bandwidth-intensive.

My suggestion would be to write a script or something to bulk-convert all your addresses to coordinates.

**Comment by 1KDevelopment** [comment]
How nice it would be if this script was built into the plugin.. hint hint ☺️

For myself I think k I've found a doable workaround. As I have my data in a Google sheet from which I import my posts, I've found this: http://stackoverflow.com/questions/22142603/how-to-get-latitude-and-longitude-for-addresses

Maybe this can help others with similar issues... 

Thanks for the reply none the less ☺️
