### ISSUE TITLE
Bug or just me: Map not working (loads grey)

### ISSUE THREAD

**Issue by 1KDevelopment** [FacetWP/facetwp-map#31]
Well .. as far as my rookie eyes can tell this shooould be working now ... but only a grey map shows up :-/ 

I've tried: 

- swithching theme to twenty sixteen
- disabling any seemingly conflicting plugins 
- checking my maps api key

I have lat and long stored in separate ACF-fields and they are formatted correctly and should work. 

I'm probably doing something wrong ... but what ? :-/ 

See the grey map in action at: http://startupcommunity.dk/resources/

**Comment by Desertsnowman** [comment]
@1KDevelopment there are a few js errors on that page, I think you should try to narrow them down a little.

**Comment by 1KDevelopment** [comment]
Thanks for having a look :-) 

I know the page i bloated and has some js violations ..but they're not the ones causing it. 

These violations are related to the theme, and i've tried both switching the theme (to twenty sixteen) and disabling all plugins. 

This removes all js errors and violations ...but the problem i still the same :-/

**Comment by 1KDevelopment** [comment]
As of now I "only" get some warnings due to the themes slow js... 

The map seems to load something ..and when dragging on the map (the grey box), it throws some errors. I've attached these in a screenshot ..but you could also check it out. 

It must be some bug with facetwp or with the map. 

Perhaps something I myself am provoking with my setup of facetwp ...but apart from the map everything works fine...

![image](https://cloud.githubusercontent.com/assets/26579270/24742306/0da43034-1aaa-11e7-81ea-45f63e19aa41.png)

**Comment by ckgg** [comment]
I had a similar issue, although my map showed an error.  I had to tweak the map API key settings, in particular the 'accept requests from these http referrers' section.  Apparently it is finicky with wildcard usage.  In my case some wildcards worked and some did not.  You can Google the details of wildcard problems.
Just mentioning it in case the issue you are having is on the Google Maps side of things.  Good luck.

**Comment by 1KDevelopment** [comment]
Thanks for the reply @ckgg 

I've tried altering the restrictions of the API. Both with wildcards, the direct url and also leaving the key open. 

It doesn't seem to work in any case :-/

**Comment by 1KDevelopment** [comment]
No good ideas @Desertsnowman  ? Would really save my weekend if you could help...

**Comment by Desertsnowman** [comment]
@1KDevelopment So osrry, I missed the reply. I'll take a look ASAP

**Comment by Desertsnowman** [comment]
@1KDevelopment I took a look, and you have no locations for that map. Can you check that the map is correctly setup ?

**Comment by 1KDevelopment** [comment]
Hi again, 

no worries... 

I have tried almost all combinations of all settings to no avail. 

When you just tried a moment ago there were no default lat + long set ..but I've had that on for a while also. 

I've now set as in attached screenshot... 

![image](https://cloud.githubusercontent.com/assets/26579270/24872224/f6cd6d1e-1e1c-11e7-8727-c9064a557ced.png)

**Comment by Desertsnowman** [comment]
@1KDevelopment I was meaning the source tab.

**Comment by JoshShashaty** [comment]
Just experienced the same thing.  What I found was that you that ACF fields aren't getting set up properly for `get_post_meta` in `get_split_location` that uses `unprefix_field` ... So, when you're selecting the lat/lng fields in the Facet WP Settings... select the actual meta field name that ACF sets up and not the ACF field that the drop down tries to help with.

I'd write a pull request to fix, but don't have the time just yet.  

Also, it'd be nice if the map displayed center with default lt/lng if there were no locations available for whatever reason.  I might be missing some context on this one though.

**Comment by mgibbs189** [comment]
@JoshShashaty thanks for the update. We'll take a look at it soon.

**Comment by mgibbs189** [comment]
Closing per #36
