### ISSUE TITLE
Same GPS coordinates

### ISSUE THREAD

**Issue by benjaminniess** [FacetWP/facetwp-map#32]
Hi,

I'm using Facet WP Map and I'm having some troubles with several posts at the exact same GPS coordinates. After zooming at the maximum value, the cluster is still here but I can't see the pins behind. 

Il there a chance that you add an extra feature to manage pins at the same coordinates? There's a lib that's supposed to do that but I couldn't find a way to plug it to the Facetwp map addon. https://github.com/jawj/OverlappingMarkerSpiderfier 

Thanks.

**Comment by ckgg** [comment]
Love the Overlapping Marker library demos!  I've never seen that behavior before, but it's really great (even if not exactly the same lat/long).  +1 for this enhancement request. :)

**Comment by mgibbs189** [comment]
We're working on a separate Map **facet** add-on: https://github.com/FacetWP/facetwp-map-facet

It includes this fix, and other improvements. Since this new plugin lets you create map facets, it also allows for different maps (with unique styling) on different pages.
