### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#33]
Nice-to-have:

The ability to create multiple maps, each one with a different data source and settings (clustering, map styling, etc).

**Comment by 61pixels** [comment]
Appreciate you adding this to the list Matt. If this was possible, FacetWP would cover absolutely all of my use-case scenarios and be used on just about all of my custom projects. I'd gladly even pay a premium for this sort of functionality built in.

**Comment by 61pixels** [comment]
I wanted to add something to this that I just found out today. Currently you technically can have multiple maps with FacetWP (as long as they all use the same style/settings like clustering etc). 

For example, I have 2 Custom Post Types. Each has their own ACF field groups associated with them. I just happened to name the ACF Google Map field the same for both 'map_address'. Even though in the FacetWP Map settings, I have the source set to ACF Group X - map_address... It still works just fine on my other post type rendering results from a different post type, using different facets and template.

So in essence I now have 2 pages, each with a FacetWP map, but showing completely different locations according to the template I've applied. I'm not sure if this was intended or not, or is just a "happy bug", but for right now this is perfect for me as all my maps are from the same area and have the same overall styles/settings. It was just the feed/source that was the big issue.

Can you guys verify if this was intended? I'd hate to move forward using this this way if it is a bug that will eventually be fixed. Basically the Source seems to ignore the actual Field Group and instead just looks at the field key itself disregarding the Group. I'm thinking maybe the Field Group is just there visually to help the user make sure they are choosing the right one? (would make total sense if so, I just never realized that)

**Comment by mgibbs189** [comment]
We're working on a separate Map **facet** add-on: https://github.com/FacetWP/facetwp-map-facet

This new plugin also allows for different maps (with unique styling) on different pages.
