### ISSUE TITLE
Option to disable scrolling when cursor is over map?

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#35]
Help Scout #6154

**Comment by Desertsnowman** [comment]
+1 on this!

**Comment by 61pixels** [comment]
There is a filter called **facetwp_map_init_args** which you could easily add in map customizations like disabling scroll wheel, etc. Would be nice to have the options in the backend sure, but for devs it's currently doable https://craigsimpson.scot/filter-facetwp-google-map-options

**Comment by mgibbs189** [comment]
Thanks for the great suggestion @61pixels -- we'll def. add this to our docs
