### ISSUE TITLE
Allowing to add custom fwpm-front.js

### ISSUE THREAD

**Issue by tbourrely** [FacetWP/facetwp-map#37]
Hi,
I was wondering why isn't it possible to override the asset fwpm-front.js, with the filter 'facetwp_assets'. 

I'd like to override the fwpm-front.js to customise the map with custom clusters and modify the marker's click event.

I would be glad if someone told me what I am missing, or if this functionality has not been made yet.

**Comment by mgibbs189** [comment]
@tbourrely it should be possible, perhaps try using a different hook priority (12 or higher)?
