### ISSUE TITLE
facetwp_map_marker_args -- what args are available?

### ISSUE THREAD

**Issue by philbraun** [FacetWP/facetwp-map#38]
Very sorry if this is a really stupid question, but: how or where can I see what args are available for facetwp_map_marker_args?
@Desertsnowman wrote [here](https://github.com/FacetWP/facetwp-map/issues/12#issuecomment-271075498) that $args['id'] and $args['icon'] are "already there", but for the life of me I can't find those in the source.
Or, to ask another way: how would one set up facetwp map to display marker icons for different categories/taxonomies? The "You would simply do a …" for ACF is, unfortunately, not very helpful for non-hardcore programmers, IMHO.

**Comment by Desertsnowman** [comment]
Hi there, 
Not a stupid question at all.
The arts are literally what Google maps have for markers. That's why they are not in the source code. Since it pushes them to Google maps, anything missing uses the defaults.

I'm on mobile so can't get the link, but do a search to find available arts for a Google map marker, and you'll see what you have.

**Comment by philbraun** [comment]
Thanks a lot for the heads-up – at least now I now I wasn't going completely mad.
However, I'm afraid still don't quite understand – where does the $args['id'] come from, and how can it be used? Your ACF comment 'You would simply do a get_field( $args['id'], 'the_field_slug')' would indicate that $args['id'] can be used as $post_id, I think, but I haven't been able to get anything to work using it this way yet.

**Comment by Desertsnowman** [comment]
I'll need to take a look when I'm at my pc again. Sorry.

**Comment by philbraun** [comment]
Is it possible there's no $args['id']?
Tried to add filter $args['label'] = $args['id'] --> no label.
Adding filter $args['label'] = $args['title'] works.

**Comment by philbraun** [comment]
Ended up adding
        $base = array(
/* added */
			'id'	   => $post_id,
/* end add */
            'title'    => get_the_title( $post_id ),
to pwf_map.php until I find a better way to get the ID of the post the filter is acted on in facetwp_map_marker_args.
