### ISSUE TITLE
Setting Lat & Longitude Bounds

### ISSUE THREAD

**Issue by JessBoctor** [FacetWP/facetwp-map#39]
Hello!

Is there a way to set Latitude and Longitudinal bounds? I have a site where the client only works in the USA, so I want the map to center on the US. Right now when the map starts I get multiple maps of the entire world.

I'm not sure if setting lat & long bounds, or if having a setting for the zoom when the map is initialized with would be the best approach. 

Your thoughts would be greatly appreciated.

Thanks!

**Comment by mgibbs189** [comment]
Hey @JessBoctor what's the URL to your map (so I can see the issue)?

Also, do you have a default lat/long set, from within the add-on's setting screen?

Thanks

**Comment by JessBoctor** [comment]
Hi Matt! 

Thanks for the quick reply!

The site is a login only, so I made a screen cast from my development version. Is there a private way I can send you the link?

In the screen cast, you can see that the map doesn't load properly initially. The zoom buttons are missing and dragging doesn't appear to work to reposition the map. 

Once I go to the fullscreen view, the zoom and street view buttons are available but there still seems to be a problem with repositioning the map.

If I go to a new filter, the map loads correctly, but still gives me repeated world maps. However, now I can zoom in and out and reposition the map. 

Also, I do have a default lat/long set to 37.09024 and 95.712891 respectively. I have my maxZoom set to 100. 

Thanks for your help!

**Comment by mgibbs189** [comment]
@JessBoctor perhaps you could create a support ticket via `Settings > FacetWP Support`?

Within the ticket, include some temporary credentials and mention this GH issue :)

**Comment by JessBoctor** [comment]
@mgibbs189 Just submitted the ticket. Thanks!

**Comment by mgibbs189** [comment]
Closing. Our new Map Facet add-on supports setting a fallback lat/lng, and also min/max zoom levels.
