### ISSUE TITLE
Include .gruntfile

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map#8]
Hey @Desertsnowman could you include the `gruntfile` in case I modify any of the JS files (so that the .min versions get generated)?

THanks

**Comment by Desertsnowman** [comment]
@mgibbs189 - I'm still working on this portion. But will add it later this week.

**Comment by Desertsnowman** [comment]
closed via cd72af38024d61a291cc2d4dd1f22e07fc11bb0a
